# Renders a real sample (PRD C6) for every built-in template.
# Samples are derived artifacts: gitignored, regenerated by CI / this script.
# Usage: pwsh tools/gen-samples.ps1   (run from repo root)
$ErrorActionPreference = "Stop"
$cli = if (Test-Path "target/release/framegeist.exe") { "target/release/framegeist.exe" }
       elseif (Test-Path "target/debug/framegeist.exe") { "target/debug/framegeist.exe" }
       else { cargo build --release -p framegeist-cli; "target/release/framegeist.exe" }
$photo = "templates/assets/test-photos/sample-landscape.jpg"
if (-not (Test-Path $photo)) { cargo run --release -p framegeist-cli --example make_test_photos }
New-Item -ItemType Directory -Force templates/samples | Out-Null
$ids = & $cli templates | ForEach-Object { ($_ -split "`t")[0] }
$done = 0; $failed = @()
foreach ($id in $ids) {
  & $cli render $photo --template $id -o "templates/samples/$id.jpg" 2>$null
  if ($LASTEXITCODE -eq 0) { $done++ } else { $failed += $id }
}
Write-Output "rendered=$done failed=$($failed.Count)"
if ($failed.Count -gt 0) { Write-Output $failed; exit 1 }
